/*
    ioHdlc - Copyright (C) 2024 Isidoro Orabona

    GNU General Public License Usage

    ioHdlc software is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ioHdlc software is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with ioHdlc software.  If not, see <http://www.gnu.org/licenses/>.

    Commercial License Usage

    Licensees holding valid commercial ioHdlc licenses may use this file in
    accordance with the commercial license agreement provided in accordance with
    the terms contained in a written agreement between you and Isidoro Orabona.
    For further information contact via email on github account.
 */

#include "ctype.h"
#include "ioHdlc.h"
#include "ioHdlclist.h"
#include <string.h>
#include <errno.h>

/**
 * HDLC core.
 */


/*===========================================================================*/
/* Module local definitions.                                                 */
/*===========================================================================*/

/*===========================================================================*/
/* Module exported variables.                                                */
/*===========================================================================*/

/*===========================================================================*/
/* Module local variables and types.                                         */
/*===========================================================================*/

/*===========================================================================*/
/* Module local functions.                                                   */
/*===========================================================================*/

static uint8_t um2supportedConnMode(uint8_t um_cmd)
{
  if (um_cmd == IOHDLC_U_SABM)
    return IOHDLC_OM_ABM;
  if (um_cmd == IOHDLC_U_SNRM)
    return IOHDLC_OM_NRM;
  return 0;
}

static uint8_t supportedConnMode2um(uint8_t mode)
{
  if (mode == IOHDLC_OM_ABM)
    return IOHDLC_U_SABM;
  if (mode == IOHDLC_OM_NRM)
    return IOHDLC_U_SNRM;
  return 0;
}

static void reply_timer_elapsed(void *peerp)
{
  iohdlc_station_peer_t *p = (iohdlc_station_peer_t *)peerp;
  iohdlc_station_t *s = p->stationp;

  /* Signal to s a reply timeout event generated by one among the peers. */
  chSysLockFromISR();
  chEvtBroadcastFlagsI(&s->cm_es, IOHDLC_EVT_C_RPLYTMO);
  chSysUnlockFromISR();
}

static void startReplyTimer(iohdlc_station_peer_t *p, uint32_t timeout_in_ms)
{
  chVTSet(&p->reply_tmo, TIME_MS2I(timeout_in_ms), reply_timer_elapsed, p);
  p->ss_state |= IOHDLC_SS_RPL_STT;
}

static void restartReplyTimer(iohdlc_station_peer_t *p, uint32_t timeout_in_ms)
{
  if (chVTIsArmed(&p->reply_tmo)) {
    chVTSet(&p->reply_tmo, TIME_MS2I(timeout_in_ms), reply_timer_elapsed, p);
    p->ss_state |= IOHDLC_SS_RPL_STT;
  }
}

static void stopReplyTimer(iohdlc_station_peer_t *p)
{
  chVTReset(&p->reply_tmo);
  p->ss_state &= ~IOHDLC_SS_RPL_STT;
}


static void ackRcvedP(iohdlc_station_peer_t *p) {
  p->stationp->pf_state &= ~IOHDLC_P_RCVED;
}

static void ackRcvedF(iohdlc_station_peer_t *p) {
  p->stationp->pf_state &= ~IOHDLC_F_RCVED;
}

static void sendUMframe(iohdlc_station_t *s, uint32_t addr, uint32_t umcmd)
{
  iohdlc_frame_t *fp;
  uint8_t *b;

  fp = hdlcTakeFrame(s->frame_pool);
  if (NULL == fp)
    return;
  b = fp->frame;
  /*
   * TODO: generalize on frame type basis
   */
  if (IOHDLC_HAS_FFF(s))
    *b++ = 5; /* FF(1) + ADDR(1) + CMD(1) + FCS(2) */
  *b++ = addr;
  *b++ = umcmd | IOHDLC_U_ID;
  fp->elen = b - fp->frame;
  hdlcSendFrame(s->driver, fp);
  hdlcReleaseFrame(s->frame_pool, fp);
}

static void clearFrameQ(iohdlc_station_peer_t *p, iohdlc_frame_q_t *q)
{
  while (!ioHdlc_frameq_isempty(q)) {
    hdlcReleaseFrame(p->stationp->frame_pool, q->next);
    ioHdlc_frameq_delete(q->next);
  }
}

static void resetPeerUm(iohdlc_station_peer_t *p)
{
  /* Reset um state variables. */
  p->um_state = 0;
  p->um_cmd = 0;
}

static void resetPeerVars(iohdlc_station_peer_t *p)
{
  /* Stop timer. */
  stopReplyTimer(p);

  /* Reset state variables. */
  p->nr = p->vr = p->vs = 0;
  p->ss_state = 0;

  /* Reset queues. */
  clearFrameQ(p, &p->i_retrans_q);
  clearFrameQ(p, &p->i_recept_q);
  clearFrameQ(p, &p->i_trans_q);
}

/*
 * @brief Check if there is a send opportunity
 * @note  In the case of normal modes, a send opportunity exists
 *        when a frame with P bit set to 1 is received if @p s is secondary or
 *        when a frame with F bit set to 1 is received if @p s is primary
 *        In the case of asynchronous modes, two-way alternate,
 *        a send opportunity exists when a idle state is detected
 *        on the line (IOHDLC_FLG_IDL).
 *        In the case of asynchronous modes, two-way simultaneous,
 *        a send opportunity ever exists.
 */
static bool thereIsSendOpportunity(iohdlc_station_t *s, uint8_t pf_bit) {
  if ((!IOHDLC_IS_NRM(s) && !(s->flags & IOHDLC_FLG_TWA)) ||
      (!IOHDLC_IS_NRM(s) && (s->flags & IOHDLC_FLG_IDL))  ||
      ( IOHDLC_IS_NRM(s) && pf_bit))
    return true;
  return false;
}

/*
 * Check timeout of reply timer in a way that
 * avoids the use of the interrupt blocking mechanism:
 * check that a timeout event was signaled and that
 * the timer was started and now is not armed.
 */
static bool checkReplyTimeout(eventflags_t ef, iohdlc_station_peer_t *p)
{
  bool r = ((ef & IOHDLC_EVT_C_RPLYTMO) &&
            (p->ss_state & IOHDLC_SS_RPL_STT) &&
            !chVTIsArmed(&p->reply_tmo));
  if (r)
    p->ss_state &= ~IOHDLC_SS_RPL_STT;
  return r;
}

/*
 * The transmitter is responsible to send the frames ready to
 * transmit, and to send frames in response to received commands
 * from the peers, based on the current state.
 */
static void transmitterTask(void *stationp) {
  iohdlc_station_t *s = (iohdlc_station_t *)stationp;
  iohdlc_station_peer_t *p;
  eventflags_t cm_flags = 0;
  event_listener_t cm_listener;

  /* Subscribe to events. */
  chEvtRegisterMaskWithFlags(&s->cm_es, &cm_listener, EVENT_MASK(0),
      IOHDLC_EVT_C_RPLYTMO|IOHDLC_EVT_UMRECVD|IOHDLC_EVT_CONNSTR|IOHDLC_EVT_LINIDLE);

  for (;/* ever */;) {

    if (!cm_flags) {
      /* Wait for the events. */
      (void) chEvtWaitAny(EVENT_MASK(0));
      cm_flags = chEvtGetAndClearFlags(&cm_listener);
    }

    /* Note: the following iteration is effective only for unbalanced mode
       in a multipoint configuration with more than one peer. */
    /* For each peer p of the input station s */
    for (p = s->peers.next; p != (iohdlc_station_peer_t *)&s->peers;
            p = p->next) {

      /* If an unnumbered command has been received, check if
         it's a (dis)connection command and action it, if possible. */
      if ((p->um_state & IOHDLC_UM_RCVED) != 0) {
        uint8_t om = um2supportedConnMode(p->um_cmd);
        uint8_t pf_bit = (p->stationp->pf_state & IOHDLC_P_RCVED) ? IOHDLC_PF_BIT : 0;

        /* Check if the command is a supported set mode and if it's
           actionable. */
        if (om) {

          /* Set mode command is actionable.
             Reset variables, change mode and send UA. */
          s->mode = om;
          resetPeerVars(p);
          p->ss_state |= IOHDLC_SS_ST_CONN; /* connected with primary/combined
                                               station */
          if (thereIsSendOpportunity(s, pf_bit)) {
            resetPeerUm(p); /* acknowledge IOHDLC_UM_RCVED */
            ackRcvedP(p);   /* acknowledge IOHDLC_P_RCVED */
            sendUMframe(s, s->addr, IOHDLC_U_UA|pf_bit);

            /* go on to eventually send other frames. The P/F has been
               acknowledged, and thus the P/F checkpoint will be inhibited  */

          } else {
            continue; /* wait respond opportunity */
          }
        } else if (p->um_cmd == IOHDLC_U_DISC) {

          /* If connected, send UA prior to actioning the DISC command
             and then change to disconnected mode. */
          if (!IOHDLC_IS_DISC(s)) {
            if (thereIsSendOpportunity(s, pf_bit)) {
              sendUMframe(s, s->addr, IOHDLC_U_UA|pf_bit);
              s->mode = IOHDLC_IS_NRM(s) ? IOHDLC_OM_NDM : IOHDLC_OM_ADM;
              resetPeerVars(p);
              resetPeerUm(p);
              ackRcvedP(p);
            }
          } else {

            /* Already disconnected. Send DM. */
            if (thereIsSendOpportunity(s, pf_bit)) {
              sendUMframe(s, s->addr, IOHDLC_U_DM|pf_bit);
              resetPeerUm(p);
              ackRcvedP(p);
            }
          }
          continue;
        } else {

          /* TODO: Change to FRMR (Frame Reject) where appropriate. */
          /* Send DM if received frame is not a set mode cmd,
             or if it is not actionable, or if it is
             not implemented. */
          p->um_cmd = 0;
          p->um_state &= ~IOHDLC_UM_RCVED;
          ackRcvedP(p);
          sendUMframe(s, s->addr, IOHDLC_U_DM|pf_bit);
          continue;
        }
      }

      /* If s is primary. */
      if (IOHDLC_IS_PRI(s)) {
        uint8_t um_cmd = p->um_cmd;

        /* if there is a new, or forced, unnumbered command to serve */
        if (um_cmd != 0 && ((cm_flags & IOHDLC_EVT_CONNSTR) ||
            !(p->um_state & IOHDLC_UM_SENT))) {

          /* If the command is a (dis)connection command and the connection state
             is correct, */
          if ((IOHDLC_PEER_DISC(p) && um2supportedConnMode(um_cmd)) ||
              (!IOHDLC_PEER_DISC(p) && (um_cmd == IOHDLC_U_DISC))) {

            /* send to p the command and keep record that it is outstanding. */
            p->um_state |= IOHDLC_UM_SENT;
            startReplyTimer(p, 100);
            sendUMframe(s, p->addr, um_cmd|IOHDLC_PF_BIT);
          } else {

            /* discard p.um_cmd if not a supported set mode cmd. */
            p->um_cmd = 0;
          }
        }
      }

      /* continue if the peer is not connected. */
      if (!(p->ss_state & IOHDLC_SS_ST_CONN))
        continue;

      /* If p.IOHDLC_PF_RCVED */
      if (!(p->stationp->pf_state & IOHDLC_PF_INHB) &&
          ((IOHDLC_IS_ABM(s) && (p->stationp->pf_state & IOHDLC_F_RCVED)) ||
          (!IOHDLC_IS_ABM(s) && (p->stationp->pf_state & (IOHDLC_P_RCVED|IOHDLC_F_RCVED))))) {
          ;
        /* Run checkpoint procedure */
      }

      /* In ABM entrambe le stazioni sono sia primarie che secondarie (combinate).
       * Se abbiamo ricevuto un comando con P impostato, allora P_RCVED è asserito, e dunque lo accettiamo
       * inviando un response con F impostato e negando P_RCVED.
       * Viceversa, se abbiamo ricevuto un response con F impostato, allora F_RCVED è asserito, e dunque
       * lo confermiamo inviando un comando con P impostato, e negando F_RCVED.
       * Quando inviamo un comando con P impostato, avviamo un reply timer che sarà fermato solo
       * al momento dell'arrivo di un frame con F impostato. Più precisamente,
       *
       * Per stazioni che inviano comandi:
       *
       * in NRM
       *    il reply timer è avviato ogni qualvolta inviamo un frame con P impostato
       *    il reply timer è reimpostato ogniqualvolta riceviamo un frame con F non impostato
       *    il reply timer è fermato quando riceviamo un frame con F impostato
       *
       * negli altri modi
       *    il reply timer è avviato ogni qualvolta inviamo un frame con P impostato
       *    solo nel caso TWA, il reply timer è reimpostato ogniqualvolta trasmettiamo un command frame
       *    il reply timer è fermato quando riceviamo un frame con F impostato
       *
       * Anche quando inviamo I-frame abbiamo un secondo timer, reply-I, azionato per il
       * recovery dell'ultimo frame in una sequenza di invio:
       *
       * in tutti i modi tranne NRM, in cui non è utilizzato
       *    il reply-I timer è avviato ogni qualvolta inviamo un I-frame
       *    solo nel caso TWA, il reply-I timer è reimpostato ogniqualvolta trasmettiamo un qualsiasi frame
       *    il reply-I timer è fermato quando riceviamo un I-frame col N(R) atteso, in pratica un N(R) che
       *    svuota la coda di ritrasmissione.
       */

      /* If s is primary/combined and (not s.IOHDLC_FLG_TWA or p.IOHDLC_F_RCVED) */
        /* Send to p RR with P bit set if p.IOHDLC_F_RCVED,
           if s is not busy and no frame to tx. */
        /* Send to p RNR with P bit set if p.IOHDLC_F_RCVED,
           if s is busy and no frame to tx. */
        /* If peer is not ready to receive, next peer */
        /* If not s.IOHDLC_FLG_TWA */
          /* Send to p all queued I frame, with P bit set if not p.IOHDLC_P_SENT. */
        /* If IOHDLC_FLG_TWA */
          /* Send to p all queued I frame, the last one with P bit set. */

      /* If secondary and p.IOHDLC_P_RCVED */
        /* Send to p RR if not busy or RNR if busy, with F bit set,
           if no frame to tx. */
        /* Send to p all queued I frame, the last one with F bit set,
           stop (with F) if p.IOHDLC_RNR_RCVED.
           Send to p RNR if become busy while sending I-frame.
           If p.IOHDLC_RNR_RCVED and no frame was sent yet, send RR or RNR. */
    }

    /* To send a frame: */
    /* Assign N(R) and P/F, if it is not a unnumbered frame. */
    /* Put the frame in the retransmission queue, if it is an I frame. */
    /* Send the frame over the physical link. */
  }
}

static void receiverTask(void *stationp) {
  iohdlc_station_t *s = (iohdlc_station_t *)stationp;
  iohdlc_station_peer_t *p;
  iohdlc_frame_t *fp;

  for (;/* ever */;) {
    uint32_t addr;
    uint8_t ctrl;
    uint8_t *foctp;
    bool is_a_command;

    /* Wait for the arrival of a frame. */
    fp = hdlcRecvFrame(s->driver, TIME_INFINITE);
    if (NULL == fp) {

      /* Idle line */
      s->flags |= IOHDLC_FLG_IDL;
      if (s->flags & IOHDLC_FLG_TWA)
        chEvtBroadcastFlags(&s->cm_es, IOHDLC_EVT_LINIDLE);
      continue;
    }
    s->flags &= ~IOHDLC_FLG_IDL;

    /* Decode addr from the frame fp.
       foctp[0] is the addr octet
       foctp[1[ is the ctrl octet */
    foctp = IOHDLC_HAS_FFF(s) ? &fp->frame[1] : &fp->frame[0];
    addr = foctp[0];
    ctrl = foctp[1];
    is_a_command = (addr == s->addr);

    /* If frame is a command in ABM, or s is secondary (NRM/ARM/NDM/ADM) */
    if (is_a_command || IOHDLC_IS_SEC(s)) {

      /* discard the frame if it isn't intended for this secondary station. */
      if (addr != s->addr)
        goto relfp;
      p = s->peers.next;

      /* Frame type is an unnumbered command.
         If the station receives more than one um commands before
         a respond opportunity occurs, it will ignore all frames received,
         except to detect the next respond opportunity, until it has sent
         a response the command */
      if (IOHDLC_IS_U_FRM(ctrl) && !(p->um_state & IOHDLC_UM_RCVED)) {

        /* Annotate that an um command has been received, record  the command,
           and signal this event to the transmitter. */
        p->um_state |= IOHDLC_UM_RCVED;
        p->um_cmd = ctrl & IOHDLC_U_FUN_MASK;
        if (ctrl & IOHDLC_PF_BIT)
          p->stationp->pf_state |= IOHDLC_P_RCVED;

        /* Signal UM_RCVED to the tx */
        chEvtBroadcastFlags(&s->cm_es, IOHDLC_EVT_UMRECVD);
      }
      goto relfp;
    }

    /* Decode peer p from the decoded frame fp. */
    p = addr2peer(s, addr);
    if (NULL == p)
      goto relfp;

    /* Mode primary (Todo: assert mode primary?) */
    if (IOHDLC_IS_PRI(s)) {

      if (IOHDLC_IS_U_FRM(ctrl)) {

        /* If p.IOHDLC_UM_SENT, aka if a UM cmd was sent by this primary
           to the peer p, then the UM frame could be a response to this UM
           cmd */
        if ((p->um_state & IOHDLC_UM_SENT) && (ctrl & IOHDLC_PF_BIT)) {
          uint8_t um_cmd;

          um_cmd = ctrl & IOHDLC_U_FUN_MASK;
          if (um_cmd == IOHDLC_U_DM) {

            /* If fp is a DM frame response, set peer as disconnected,
               stop p timeout, clear um_cmd and IOHDLC_UM_SENT and set
               a disconnected response. */
            p->um_cmd = 0;
            p->um_state &= ~IOHDLC_UM_SENT;     /* Acknowledge UM_SENT. */
            p->ss_state &= ~IOHDLC_SS_ST_CONN;  /* Cancel connected state. */
            p->ss_state |= IOHDLC_SS_ST_DISM;   /* Set disconnected response. */
            stopReplyTimer(p);
            chEvtBroadcastFlags(&s->cm_es, IOHDLC_EVT_CONNCHG);
          } else if (um_cmd == IOHDLC_U_UA) {
            uint8_t om;

            /* If UA frame response, clear all vars of p. Set new mode, if any,
               of this primary and signal the completion of the (dis)connection
               attempt. */
            if ((om = um2supportedConnMode(p->um_cmd)) != 0) {
              resetPeerVars(p);
              resetPeerUm(p);
              s->mode = om;
              p->ss_state |= IOHDLC_SS_ST_CONN;
            } else if (p->um_cmd == IOHDLC_U_DISC) {
              resetPeerVars(p);
              resetPeerUm(p);
              om = IOHDLC_IS_NRM(s) ? IOHDLC_OM_NDM : IOHDLC_OM_ADM;
              s->mode = om;
            } else {
              /* Assert here */
            }
            p->stationp->pf_state |= IOHDLC_F_RCVED|IOHDLC_PF_INHB;
            chEvtBroadcastFlags(&s->cm_es, IOHDLC_EVT_CONNCHG|IOHDLC_EVT_UMRECVD);
          }
        }
        goto relfp;
      }
    }

relfp:
    hdlcReleaseFrame(s->frame_pool, fp);
  }
}

/*===========================================================================*/
/* Module exported functions.                                                */
/*===========================================================================*/

iohdlc_station_peer_t *addr2peer(iohdlc_station_t *ioHdlcsp, uint32_t peer_addr) {
  iohdlc_station_peer_t *ssp = (iohdlc_station_peer_t *)&ioHdlcsp->peers;

  while (ssp->next != (iohdlc_station_peer_t *)&ioHdlcsp->peers) {
    ssp = ssp->next;
    if ((uint32_t)ssp->addr == peer_addr)
      return ssp;
  }
  return NULL;
}

/**
 *
 * @note  Only one secondary station at a time shall be put in
 *        asynchronous response mode (see 6.11.3.1)
 */
int32_t ioHdlcStationLinkUp(iohdlc_station_t *ioHdlcsp, uint32_t peer_addr, uint8_t mode) {
  iohdlc_station_peer_t *p = addr2peer(ioHdlcsp, peer_addr);
  event_listener_t cm_listener;
  eventflags_t eflags;
  int32_t r = 0;
  uint8_t um_cmd;
  int i;

  /* Check if down */
  if (NULL == p || (p->ss_state & IOHDLC_SS_ST_CONN)) {
    ioHdlcsp->errorno = EISCONN;
    return -1;
  }

  /* If the input station is a secondary one, nothing to do. */
  if (IOHDLC_IS_SEC(ioHdlcsp))
    return 0;

  um_cmd = supportedConnMode2um(mode);
  if (um_cmd == 0) {
    ioHdlcsp->errorno = EINVAL;
    r = -1;
    goto eex2;
  }

  chEvtRegisterMaskWithFlags(&ioHdlcsp->cm_es, &cm_listener, EVENT_MASK(0),
      IOHDLC_EVT_CONNCHG|IOHDLC_EVT_C_RPLYTMO);

  for (i = 0; i < 3; ++i) {
    /* Send SM mode */

    p->um_cmd = um_cmd;
    p->ss_state &= ~IOHDLC_SS_ST_DISM;
    chEvtBroadcastFlags(&ioHdlcsp->cm_es, IOHDLC_EVT_CONNSTR);

    do {
      /* Wait connection completed from the peer or timeout event */
      (void) chEvtWaitAnyTimeout(EVENT_MASK(0), TIME_INFINITE);
      eflags = chEvtGetAndClearFlags(&cm_listener);

      if ((p->ss_state & IOHDLC_SS_ST_DISM)) {
        ioHdlcsp->errorno = ECONNREFUSED;
        goto eex2;
      }

      /* check if completed */
      if (p->ss_state & IOHDLC_SS_ST_CONN)
        /* Link up, station connected with the peer. */
        goto eex;

      /* if no response from peer, retry */
      if (checkReplyTimeout(eflags, p)) {
        ioHdlcsp->errorno = ETIMEDOUT;
        break;
      }
    } while (true);
  }
eex2:
  r = -1;

eex:
  chEvtUnregister(&ioHdlcsp->cm_es, &cm_listener);
  return r;
}

int32_t ioHdlcStationLinkDown(iohdlc_station_t *ioHdlcsp, uint32_t peer_addr) {
  iohdlc_station_peer_t *p = addr2peer(ioHdlcsp, peer_addr);
  event_listener_t cm_listener;
  eventflags_t eflags;
  int32_t r = 0;
  int i;

  /* Check if up */
  if (NULL == p || !(p->ss_state & IOHDLC_SS_ST_CONN)) {
    ioHdlcsp->errorno = ENOTCONN;
    return -1;
  }

  /* If the input station is a secondary one, nothing to do. */
  if (IOHDLC_IS_SEC(ioHdlcsp))
    return 0;

  chEvtRegisterMaskWithFlags(&ioHdlcsp->cm_es, &cm_listener, EVENT_MASK(0),
      IOHDLC_EVT_CONNCHG|IOHDLC_EVT_C_RPLYTMO);

  for (i = 0; i < 3; ++i) {
    /* Send DISC */
    p->um_cmd = IOHDLC_U_DISC;

    chEvtBroadcastFlags(&ioHdlcsp->cm_es, IOHDLC_EVT_CONNSTR);

    p->ss_state &= ~IOHDLC_SS_ST_DISM;
    do {
      /* Wait disconnection completed from the peer or timeout event */
      (void) chEvtWaitAnyTimeout(EVENT_MASK(0), TIME_INFINITE);
      eflags = chEvtGetAndClearFlags(&cm_listener);

      if ((p->ss_state & IOHDLC_SS_ST_DISM)) {
        ioHdlcsp->errorno = ENOTCONN;
        goto eex2;
      }

      /* check if completed */
      if (!(p->ss_state & IOHDLC_SS_ST_CONN))
        /* Link down, station disconnected from the peer. */
        goto eex;

      /* if no response from peer, retry */
      if (checkReplyTimeout(eflags, p)) {
        ioHdlcsp->errorno = ETIMEDOUT;
        break;
      }
    } while (true);
  }
eex2:
  r = -1;

eex:
  chEvtUnregister(&ioHdlcsp->cm_es, &cm_listener);
  return r;
}

int32_t ioHdlcWrite(iohdlc_station_peer_t *peerp, const void *buf, size_t count) {
  iohdlc_station_t *ioHdlcsp = peerp->stationp;
  (void)buf;
  (void)count;

  switch (ioHdlcsp->mode) {
  default:
    return -1; /* EBADF, peer not connected. */
  }
  return 0;
}

int32_t ioHdlcRead(iohdlc_station_peer_t *peerp, void *buf, size_t count) {
  iohdlc_station_t *ioHdlcsp = peerp->stationp;
  (void)buf;
  (void)count;

  switch (ioHdlcsp->mode) {
  default:
    return -1; /* EBADF, peer not connected. */
  }
  return 0;
}

/*
 * @brief   Initialize and add a peer to a hdlc station.
 *
 * @param[in] ioHdlcsp  pointer to the @p iohdlc_station_t structure
 * @param[in] peer      pointer to the @p iohdlc_station_peer_t structure
 * @param[in] addr      the address of the peer on the station data link.
 * @param[in] mifl      the maximum information field length.
 *
 * @return              success or error
 * @retval  0           if the peer is successfully added to the station
 * @retval -1           in case of errors, and the station errorno is set
 *                      to the specific error.
 */
int32_t ioHdlcAddPeer(iohdlc_station_t *ioHdlcsp, iohdlc_station_peer_t *peer,
                      uint32_t addr, uint32_t mifl) {
  if (!(ioHdlcsp->flags & IOHDLC_FLG_PRI) &&
      (ioHdlcsp->mode != IOHDLC_OM_NDM) && (ioHdlcsp->mode != IOHDLC_OM_ADM)) {
    ioHdlcsp->errorno = EINVAL;
    return -1;  /* EINVAL, secondary station not initialized or already
                   connected.*/
  }

  /* Check that addr does not already exist. */
  if (addr2peer(ioHdlcsp, addr) != NULL) {
      ioHdlcsp->errorno = EEXIST;
      return -1;
  }

  /* Init the peer. */
  memset(peer, 0, sizeof *peer);
  peer->addr = addr;
  peer->stationp = ioHdlcsp;
  peer->kr = peer->ks = (1 << ioHdlcsp->modulus) - 1;
  peer->miflr = peer->mifls = mifl;
  peer->poll_retry_max = 3;  /* Default: max 3 retries before declaring link down. */
  ioHdlc_frameq_init(&peer->i_recept_q);
  ioHdlc_frameq_init(&peer->i_retrans_q);
  ioHdlc_frameq_init(&peer->i_trans_q);
  chVTObjectInit(&peer->reply_tmr.vt);
  peer->reply_tmr.expired = false;
  chVTObjectInit(&peer->i_reply_tmr.vt);
  peer->i_reply_tmr.expired = false;

  /* Add the peer to the station. */
  ioHdlc_peerl_insert(&ioHdlcsp->peers, peer);
  return 0;
}

/*
 * @brief   Initialize an hdlc station.
 * @details After the initialization, the operational mode of
 *          the station is NDM or ADM and the station is defined as primary or
 *          secondary.
 * @note    Currently, only modulus 8 is supported.
 *
 * @param[in] ioHdlcsp  pointer to the @p iohdlc_station_t structure
 *
 * @retval    -1        if error
 * @retval     0        if success
 *
 */
int32_t ioHdlcStationInit(iohdlc_station_t *ioHdlcsp,
                          const iohdlc_station_config_t *ioHdlcsconfp) {
  uint32_t mod2 = 0;
  uint8_t modulus = ioHdlcsconfp->modulus;
  uint8_t mode = ioHdlcsconfp->mode;

  ioHdlcsp->addr = ioHdlcsconfp->addr;
  ioHdlcsp->flags = ioHdlcsconfp->flags;

  /* mod2 = log2(modulus) */
  while (modulus >>= 1)
    ++mod2;

  if ((mode != IOHDLC_OM_NDM) && (mode != IOHDLC_OM_ADM)) {
    ioHdlcsp->errorno = EINVAL;
    return -1;
  }
  ioHdlcsp->mode = mode;
  ioHdlcsp->modulus = mod2;
  ioHdlcsp->pfoctet = (mod2 + 1) / 8;
  ioHdlcsp->frame_pool = ioHdlcsconfp->fpp;
  ioHdlc_frameq_init(&ioHdlcsp->ni_recept_q);
  ioHdlc_frameq_init(&ioHdlcsp->ni_trans_q);
  ioHdlc_peerl_init(&ioHdlcsp->peers);
  ioHdlcsp->driver = ioHdlcsconfp->driver;
  chEvtObjectInit(&ioHdlcsp->cm_es);

  /* Set default options. */
  ioHdlcsp->optfuncs[IOHDLC_OPT_REJ_OCT] |= IOHDLC_OPT_REJ;
  ioHdlcsp->optfuncs[IOHDLC_OPT_SST_OCT] |= IOHDLC_OPT_SST;
  ioHdlcsp->optfuncs[IOHDLC_OPT_STB_OCT] |= IOHDLC_OPT_STB;
  ioHdlcsp->optfuncs[IOHDLC_OPT_FFF_OCT] |= IOHDLC_OPT_FFF;
  hdlcHasFrameFormat(ioHdlcsp->driver, true);
  hdlcApplyTransparency(ioHdlcsp->driver, false);
  //hdlcApplyTransparency(driver, true);

  /* Start driver */
  hdlcStart(ioHdlcsp->driver, ioHdlcsconfp->phydriver, ioHdlcsconfp->phydriver_config,
      ioHdlcsconfp->fpp);

  /* Create receiver and trasmitter task */
  chThdCreateFromHeap(NULL, 2048, "TX", NORMALPRIO + 1, transmitterTask, ioHdlcsp);
  chThdCreateFromHeap(NULL, 2048, "RX", NORMALPRIO + 1, receiverTask, ioHdlcsp);
  return 0;
}
